// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Asset", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("InstallationDate").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("LastMaintenanceDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Metadata").IsRequired().HasColumnType("text");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<string>("Type").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Assets");

                b.OwnsOne("Domain.ValueObjects.Capacity", "Capacity", b1 =>
                {
                    b1.Property<Guid>("AssetId").HasColumnType("uuid");
                    b1.Property<string>("Unit").IsRequired().HasDefaultValue("MW").HasColumnType("text").HasColumnName("CapacityUnit");
                    b1.Property<double>("Value").HasColumnType("double precision").HasColumnName("CapacityValue");
                    b1.HasKey("AssetId");
                    b1.ToTable("Assets");
                    b1.WithOwner().HasForeignKey("AssetId");
                });

                b.OwnsOne("Domain.ValueObjects.GeographicLocation", "Location", b1 =>
                {
                    b1.Property<Guid>("AssetId").HasColumnType("uuid");
                    b1.Property<double?>("Elevation").HasColumnType("double precision").HasColumnName("Elevation");
                    b1.Property<double>("Latitude").HasColumnType("double precision").HasColumnName("Latitude");
                    b1.Property<double>("Longitude").HasColumnType("double precision").HasColumnName("Longitude");
                    b1.HasKey("AssetId");
                    b1.ToTable("Assets");
                    b1.WithOwner().HasForeignKey("AssetId");
                });

                b.Navigation("Capacity").IsRequired();
                b.Navigation("Location").IsRequired();
            });

            modelBuilder.Entity("Domain.Entities.MaintenanceSchedule", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("AssetId").HasColumnType("uuid");
                b.Property<DateTime?>("CompletedDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Notes").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<DateTime>("ScheduledDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.ToTable("MaintenanceSchedules");
            });
#pragma warning restore 612, 618
        }
    }
}
